//引入头文件
#include "hal_data.h"
#include "PWM.h"
#include "action.h"
#include "oled.h"
#include "bmp.h"
#include "Face.h"
//模式定义区
#define Stand_mode 0        //站立
#define Sleep_mode 1        //睡觉
#define Forward_mode 2      //前进
#define Turn_Left_mode 3    //左转
#define Turn_Right_mode 4   //右转
#define Tail_mode 5         //摇尾巴
#define Shake_Hand_mode 6   //握手
#define Gasp_mode 7         //哈气



FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER


uint8_t MODE[1];
uint8_t Flag = 0;
void Blue_Tooth_Callback(uart_callback_args_t *p_args)
{
    if(p_args->event == UART_EVENT_RX_COMPLETE)
    {
        Flag = 1;
        MODE[0] = MODE[0] - '0';
        //R_SCI_UART_Write(&Blue_Tooth_ctrl,MODE,1);//开启串口接收
    }
}

//IIC回调函数
fsp_err_t err = FSP_SUCCESS;
i2c_master_event_t i2c_event = I2C_MASTER_EVENT_ABORTED;
uint32_t timeout_ms = 1000000;
void OLED_callback(i2c_master_callback_args_t *p_args)
{
    i2c_event = I2C_MASTER_EVENT_ABORTED;
    if (NULL != p_args)
    {
        i2c_event = p_args->event;
    }
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
     //R_Front_Init();//初始化右前腿
     Front_Init();//初始化前腿
     R_Rear_Init();//初始化右后腿
     L_Rear_Init();//初始化左后腿
     Tail_Init();//初始化尾巴

     R_IIC_MASTER_Open(&OLED_ctrl,&OLED_cfg);//开启IIC

     OLED_Init();//初始化屏幕
     OLED_Clear();//清屏
     OLED_ColorTurn(0);//正常显示
     OLED_DisplayTurn(1);//正常方向
     OLED_Clear();//清屏

     R_SCI_UART_Open(&Blue_Tooth_ctrl,&Blue_Tooth_cfg);//开启串口
     R_SCI_UART_Read(&Blue_Tooth_ctrl,MODE,1);//开启串口接收

     OLED_ShowPicture(0,0,70,70,SMILE,1);//显示图片
     OLED_Refresh();
     stand();
     while (1)
     {

         if(Flag == 1)
         {
             Flag = 0;
             switch(MODE[0])//行为模式判别
             {
                 case Stand_mode:
                     Face_Stand();
                     OLED_ShowPicture(0,0,70,70,SMILE,1);//显示图片
                     OLED_Refresh();
                     stand();
                     break;
                 case Sleep_mode:
                     sleep();
                     Face_Sleep();
                     OLED_ShowPicture(0,0,70,70,SLEEP,1);//显示图片
                     OLED_Refresh();
                     break;
                 case Forward_mode:
                     Face_Forward();//显示前进
                     OLED_ShowPicture(0,0,70,70,RUN,1);//显示图片
                     OLED_Refresh();
                     Forward_OLD();
                     stand();
                     break;
                 case Turn_Left_mode:
                     Face_Turnleft();
                     OLED_ShowPicture(0,0,70,70,RUN,1);//显示图片
                     OLED_Refresh();
                     Turn_Left();
                     break;
                 case Turn_Right_mode:
                     Face_TurnRight();
                     OLED_ShowPicture(0,0,70,70,RUN,1);//显示图片
                     OLED_Refresh();
                     Turn_Right();
                     break;
                 case Tail_mode:
                     Face_Tail();
                     OLED_ShowPicture(0,0,70,70,SMILE,1);//显示图片
                     OLED_Refresh();
                     Shake_Tail();
                     break;
                 case Shake_Hand_mode:
                     Face_Hand();
                     OLED_ShowPicture(0,0,60,60,HAND,1);//显示图片
                     OLED_Refresh();
                     Shake_Hand();
                     break;
                 case Gasp_mode:
                     Gasp();
                     break;
                 default:
                     break;
             }
             R_SCI_UART_Read(&Blue_Tooth_ctrl,MODE,1);//开启串口接收
         }

         R_BSP_SoftwareDelay(20, BSP_DELAY_UNITS_MILLISECONDS);

     }



#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
